services:
  db:
    ports:
      - "5432:5432"

  backend:
    volumes:
      - ./backend:/app
      - /app/node_modules
    ports:
      - "3000:3000"

  frontend:
    volumes:
      - ./frontend/react-app:/app
      - /app/node_modules
    ports:
      - "5173:5173"

  pgadmin:
    image: dpage/pgadmin4
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.com
      PGADMIN_DEFAULT_PASSWORD: admin
    ports:
      - "8080:80"
    depends_on:
      - db
